modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="fishtrap" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Fish Trap" #mandatory
description='''
A hopefully simple implementation of a semi automatic fish trap.
'''

